### ISSUE TITLE
Bug: Unit Test for MacOS has failed

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro-Int-Gymnasium#4]
**1 Describe the bug**

**2 To Reproduce**

**3 Expected behavior**

**4 Screenshots**

**5 Additional Informations**
![image](https://github.com/fhswf/MLPro-Int-Gymnasium/assets/88610818/313e151c-3c24-401a-96bd-a160f6e7e837)
![image](https://github.com/fhswf/MLPro-Int-Gymnasium/assets/88610818/2eb92bd5-a0b9-4057-bacf-0e518d8d610e)

5.1 Operating System
   - [ ] Linux
   - [ ] Windows
   - [ ] Mac OS

**Comment by detlefarend** [comment]
In our today's sprint planning we opted for variant 2...
