### ISSUE TITLE
Bug: Errors on other enviroments than classic control

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro-Int-Gymnasium#5]
**1 Describe the bug**
If we run gymnasium environments that do not belong to classic control, then it always throws an error. The errors for each environment are unique. This could be because different behaviour of each environment, which does not meet the standard requirements of MLPro-RL. Therefore, we need to further analyse this and find solutions, e.g. make the MLPro-RL more flexible towards different gymnasium environments or create a pool of gymnasium environments in MLPro-Int-Gymnasium.

**2 To Reproduce**
1. Open "howto_rl_agent_002_train_agent_with_own_policy_on_gym_environment.py" in MLPro-Int-Gymnasium
2. Change the environment of 'CartPole-v1' to another environment (not from classic control)
3. Run the training

**3 Expected behavior**
1. 'FrozenLake-v1'
![image](https://github.com/fhswf/MLPro-Int-Gymnasium/assets/88610818/b2ba1e14-48bb-4a9e-bacc-a194c7a73aa4)

2. 'CliffWalking-v0'
![image](https://github.com/fhswf/MLPro-Int-Gymnasium/assets/88610818/ca257cdc-d1e6-4fe8-b508-3768191c98b9)

**4 Screenshots**
See Point 3...

**5 Additional Informations**

5.1 Operating System
   - [ ] Linux
   - [x] Windows
   - [ ] Mac OS

**Comment by detlefarend** [comment]
As discussed today we will add an exception for the user to make clear that the problem is on the environment and not MLPro.
